---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fteam
  namespace: open-cluster-management-global-set
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-all-openshift
        requeueAfterSeconds: 180
  template:
    metadata:
      name: fteam-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: fteam-ci-cd
        server: "{{server}}"
      project: default
      source:
        path: team-gitops-policy
        repoURL: https://github.com/eformat/acm-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          preserveResourcesOnDeletion: false
        syncOptions:
          - CreateNamespace=true
