---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fteam
  namespace: open-cluster-management-global-set
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-all-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: fteam-{{name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      finalizers:
      - argoproj.io/finalizer
    spec:
      project: default
      destination:
        server: "{{server}}"
        namespace: fteam-ci-cd
      source:
        repoURL: https://github.com/eformat/acm-gitops.git
        path: team-gitops-policy
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
