---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: zteam 
  namespace: open-cluster-management-global-set
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: open-cluster-management-global-set 
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: placement-team-argo
    namespace: zteam-ci-cd
