---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-gitops
policyDefaults:
  placement:
    placementName: placement-all-openshift
  remediationAction: enforce
  configurationPolicyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: open-cluster-management-global-set
  severity: medium
  standards:
    - generic
policies:
  - name: fteam-gitops
    manifests:
      - path: fteam-argocd-cr.yaml
