---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: argocd-teams
placementBindingDefaults:
  name: argocd-teams
policyDefaults:
  placement:
    placementName: placement-team-argo
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls: 
    - CM-2 Baseline Configuration
  consolidateManifests: true
  disabled: false
  namespace: open-cluster-management-global-set
  remediationAction: enforce
  pruneObjectBehavior: "DeleteAll"
  severity: medium
  standards:
    - generic
policies:
  - name: fteam-gitops
    manifests:
      - path: fteam-argocd-cr.yaml
